version: '3.8'
services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 1337:3306

  PhpMyAdmin:
    image: nazarpc/phpmyadmin
    ports:
      - "8090:80"
    links:
      - db:mysql

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - "db:tiw"

